/* Public portfolio descriptions follow the company's website. No numerical
   specification or regulatory approval is implied by a family-level guide. */
window.TRF = {
  email: 'hi@darianzhao.com',
  materials: [
    {id:'TPE',name:'Thermoplastic elastomer',summary:'Versatile softness, flexibility and processing',traits:'Hardness · recovery · molding',description:'A starting point for flexible parts, seals and soft-touch applications. Discuss the required balance between softness, recovery and manufacturing behavior.',questions:['Target hardness and the test method','Part geometry, fit and compression conditions','Injection molding or extrusion process','Contact medium, temperature and applicable tests']},
    {id:'TPV',name:'Thermoplastic vulcanizate',summary:'Heat, weather exposure and durable sealing',traits:'Service temperature · exposure · sealing',description:'A family to discuss for durable elastomer components exposed to heat or outdoor conditions. The service environment and sealing requirements determine which grade should be evaluated.',questions:['Continuous and peak service temperatures','Outdoor exposure and contact fluids','Compression and recovery requirements','Geometry, processing method and acceptance tests']},
    {id:'TPU',name:'Thermoplastic polyurethane',summary:'Toughness with flexibility',traits:'Mechanical demands · wear · processing',description:'Discuss TPU-based materials when the part needs a combination of toughness and flexibility. A specific grade must be evaluated against the actual mechanical and environmental requirements.',questions:['Loads, movement and required mechanical properties','Wear conditions and contact media','Humidity and service temperature','Processing method, color and dimensional targets']},
    {id:'TPSiV',name:'Silicone-modified elastomer',summary:'Refined touch and surface appearance',traits:'Feel · surface · end-use conditions',description:'Explore silicone-modified elastomers for applications prioritizing tactile feel and appearance. Confirm the grade’s processing guidance, compatibility and performance in your finished part.',questions:['Surface feel and appearance targets','Substrate and assembly requirements','Contact, cleaning and use conditions','Processing method and validation tests']}
  ],
  applications: {
    packaging:{label:'Packaging — caps, liners & stoppers',title:'A seal that fits your packaging.',families:'Start the discussion with TPE',description:'For caps, liners and stoppers, define the seal interface, opening force and actual contact conditions before choosing a grade.',questions:['Part drawing and mating dimensions','Contents, contact time and temperature','Opening / closing force and leak-test requirements'],note:'Food-contact suitability must be assessed for the exact grade, destination market and actual use conditions.'},
    pharmaceutical:{label:'Pharmaceutical packaging — contact components',title:'Define the contact. Then select the compound.',families:'Discuss application-specific TPE compounds',description:'For pharmaceutical packaging, start with the function of the component and whether it contacts the drug. Share the formulation or contact medium, storage conditions and manufacturing process so the discussion can focus on an appropriate candidate material and test plan.',questions:['Component drawing, sealing function and drug-contact conditions','Storage temperature, contact duration and sterilization if applicable','Destination market, required tests and grade-specific documentation'],note:'Pharmaceutical packaging suitability is specific to the material grade and intended use. Agree the required documentation and validate the finished packaging system.'},
    medical:{label:'Medical — plungers & seals',title:'Material selection starts with use conditions.',families:'Discuss application-specific TPE compounds',description:'For medical plungers and seals, begin with the device geometry, pressure, speed and fluid. Agree the required tests before evaluating sample material.',questions:['Seal drawing, pressure and operating speed','Contact fluid and sterilization conditions','Required device, material and performance tests'],note:'A material-family description does not establish medical device suitability. Confirm grade-specific documentation and validate the finished component.'},
    automotive:{label:'Automotive & industrial components',title:'Define the environment. Then the compound.',families:'Discuss TPV, TPE or TPU',description:'For automotive interior and exterior parts, describe what the component must withstand over its service life. Candidate materials depend on heat, contact fluids, movement and the required sealing or mechanical function.',questions:['Service temperature and contact media','Sealing, recovery or mechanical requirements','Part drawing, process and acceptance criteria'],note:'Family selection is preliminary. Properties and processing conditions must be confirmed for the candidate grade.'},
    cable:{label:'Wire & cable',title:'Flexibility built around the cable.',families:'Discuss TPE or TPU compounds',description:'For specialty wire and cable, start with the cable construction, flexibility target and operating environment. Share the relevant test requirements and extrusion conditions.',questions:['Cable construction and jacket dimensions','Bending, abrasion and environmental requirements','Extrusion setup and required electrical / flame tests'],note:'Electrical performance, flame rating and other requirements need grade-specific documentation and finished-cable testing.'},
    consumer:{label:'Consumer products & soft-touch parts',title:'Make the feel part of the specification.',families:'Discuss TPE, TPU or TPSiV',description:'Describe the intended feel, appearance and manufacturing process. Include the substrate if you are molding onto another material.',questions:['Hardness, tactile feel and appearance targets','Substrate, tooling and processing method','Contact conditions, cleaning and durability tests'],note:'Adhesion and surface performance depend on the particular formulation, substrate and processing conditions.'}
  },
  priorities:{fit:{label:'Sealing & fit',prompt:'Define mating dimensions, compression and acceptable opening or operating force.'},touch:{label:'Soft touch',prompt:'Describe target hardness, surface texture, grip and your reference sample.'},durability:{label:'Durability',prompt:'Specify service temperature, contact media, repeated loading and target test results.'},processing:{label:'Processing',prompt:'Share your process, tooling, current grade and the production issue to solve.'}},
  videos:{
    packaging:{src:'./assets/bottle-stoppers-vi.mp4',title:'TPE for T-shaped bottle stoppers',poster:'./assets/bottle-video-poster.jpg',transcript:'English summary: Is the stopper too tight or too loose? Review how it fits the bottle neck. TERRIFIC produces TPE raw materials for bottle stoppers. Share the drawing, bottle neck diameter and opening requirements to discuss material selection.'},
    medical:{src:'./assets/medical-seals-en.mp4',title:'Power-injector syringe seals',poster:'./assets/medical-video-poster.jpg',transcript:'Manufacturing power-injector syringe seals? Material selection starts with your operating pressure, injection speed and fluid. Terrific develops and produces TPE compounds for medical seals. Share your seal drawing and test requirements. Let’s discuss a material trial around your actual operating conditions.'}
  }
};
